[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"
access-control-allow-origin="mysite.example.com"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "10.10.10.2:2181", "10.10.10.3:2181", "10.10.10.4:2181" ]
timeout=6
root-path="/burrow"

[client-profile.test]
client-id="burrow-test"
kafka-version="0.10.0"

[cluster.local]
class-name="kafka"
servers=[ "10.10.10.2:9092", "10.10.10.2:9092", "10.10.10.2:9092" ]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.local]
class-name="kafka"
cluster="local"
servers=[ "10.10.10.2:9092", "10.10.10.2:9092", "10.10.10.2:9092" ]
client-profile="test"
group-blacklist=""
group-whitelist="^.*logstash.*$"

[cluster.insolar]
class-name="kafka"
servers=[ "kafka1-insolar.gce.inaccess.com:9092", "kafka2-insolar.gce.inaccess.com:9092", "kafka3-insolar.gce.inaccess.com:9092" ]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.insolar]
class-name="kafka"
cluster="insolar"
servers=[ "kafka1-insolar.gce.inaccess.com:9092", "kafka2-insolar.gce.inaccess.com:9092", "kafka3-insolar.gce.inaccess.com:9092" ]
client-profile="test"
group-blacklist=""
group-whitelist="^.*collaborative.*$"

#[consumer.local_zk]
#class-name="kafka_zk"
#cluster="local"
#servers=[ "10.10.10.2:2181", "10.10.10.3:2181", "10.10.10.4:2181" ]
#zookeeper-path="/kafka-cluster"
#zookeeper-timeout=30
##group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
#group-blacklist=""
#group-whitelist="^.*collaborative.*$"

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=5
intervals=3
expire-group=86400
min-distance=1
group-whitelist="^.*(collaborative|logstash).*$"

#[notifier.default]
#class-name="http"
#url-open="http://someservice.example.com:1467/v1/event"
#interval=60
#timeout=5
#keepalive=30
#extras={ api_key="REDACTED", app="burrow", tier="STG", fabric="mydc" }
#template-open="config/default-http-post.tmpl"
#template-close="config/default-http-delete.tmpl"
#method-close="DELETE"
#send-close=true
#threshold=1
